name: CI Pipeline

on: [push, pull_request]

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
    
    - name: Set up Node.js
      uses: actions/setup-node@v3
      with:
        node-version: 20
    
    - name: Install dependencies
      run: npm install
    
    - name: Fix Mocha permission
      run: chmod +x ./node_modules/.bin/mocha

    - name: Run unit tests
      run: npm test
    
    - name: Run OWASP Dependency Check
      uses: dependency-check/Dependency-Check_Action@main
      with:
        project: "WebApp"
        path: "."
        format: "HTML"
        out: "dependency-check-report"
    
    - name: Upload Dependency Check Report
      uses: actions/upload-artifact@v4
      with:
        name: Dependency-Check-Report
        path: dependency-check-report
        

    
    - name: Start Web Application
      run: npm start &

    - name: Run Selenium UI Tests
      uses: actions/setup-java@v3
      with:
        java-version: '11'
        distribution: 'temurin'
    
    - name: Start Selenium Server
      run: |
        docker run -d -p 4444:4444 --name selenium-server selenium/standalone-chrome
        sleep 10 # Wait for server to start
        
    - name: Run UI Tests
      run: |
        npm install selenium-webdriver
        node tests/ui-test.js


    - name: Run ESLint Security Scan
      run: |
          mkdir -p reports
          chmod +x ./node_modules/.bin/eslint
          ./node_modules/.bin/eslint . --ext .js --format json --output-file reports/eslint-report.json
          ./node_modules/.bin/eslint . --ext .js --format @microsoft/eslint-formatter-sarif --output-file reports/eslint-results.sarif

    - name: Run SonarQube Scan
      env:
        SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}
        SONAR_HOST_URL: ${{ secrets.SONAR_HOST_URL }}
      run: |
        docker run --rm --network host \
          -v "$(pwd):/usr/src" \
          sonarsource/sonar-scanner-cli \
          -Dsonar.projectKey=webapp \
          -Dsonar.sources=/usr/src \
          -Dsonar.host.url=$SONAR_HOST_URL \
          -Dsonar.login=$SONAR_TOKEN